name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "deno.json"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: test
        run: deno test --allow-net
