name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "deno.json"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: test
        run: deno test --allow-net

      - name: Publish package
        run: npx jsr publish
